name: End-To-End Tests

on: pull_request

jobs:
  cypress:
    name: Cypress Ubuntu
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node_version: "lts/hydrogen"
      - run: npm ci
      - uses: cypress-io/github-action@v6
        with:
          build: npm run build
          start: npm start
